all:
  children:
    database:
      hosts:
        database-server:
          ansible_host: 3.255.208.199
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_devops

    backend:
      hosts:
        backend-server:
          ansible_host: 34.245.207.169
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_devops

    frontend:
      hosts:
        frontend-server:
          ansible_host: 52.210.93.156
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa_devops

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
